apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-k8s
  name: hello-k8s
spec:
  containers:
  - image: nginx
    name: hello-k8s
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
